name: Sync GitHub to Azure Repos

on:
  push:
    branches:
      - main  # Ou a branch que deseja sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --global user.email "henrisrs@hotmail.com"
          git config --global user.name "sidneihenrique"

      - name: Adicionar remoto do Azure
        run: |
          git remote add azure https://$(echo "${{ secrets.TOKEN_AZURE }}")@dev.azure.com/pucpr-estudantes/prj-bsi-7u-e03/_git/umlthegame
          git fetch azure
          git pull --rebase azure main || echo "Branch main ainda não existe no Azure."
          git push azure main --force
